[workspace]
resolver = "2"
members = [
    "crates/mold-geometry",
    "crates/mold-manifold",
    "crates/mold-core",
    "crates/mold-shell",
    "crates/mold-cli",
    "crates/mold-test-models",
]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
rust-version = "1.85"

[workspace.dependencies]
manifold-rust = "0.9.2"
stl_io = "0.11.0"
mold-geometry = { path = "crates/mold-geometry" }
mold-manifold = { path = "crates/mold-manifold" }
mold-core = { path = "crates/mold-core" }
mold-shell = { path = "crates/mold-shell" }
mold-test-models = { path = "crates/mold-test-models" }
